### ISSUE TITLE
1.06 .tsv export

### ISSUE THREAD

**Issue by FEARka** [pashok6798/TTG_Tools#10]
TTG Tools 1.06 .tsv export doesn't work.

**Comment by pashok6798** [comment]
Wow! I even didn't know that someone use that option. I'll check it later. I don't have much time now.

**Comment by pashok6798** [comment]
[TTG Tools 1.0.6 fix.zip](https://github.com/pashok6798/TTG_Tools/files/6052249/TTG.Tools.1.0.6.fix.zip)
Try this fix.

**Comment by FEARka** [comment]
It's working. Thank you.
