### ISSUE TITLE
New TFTB - S3 Atlastower

### ISSUE THREAD

**Issue by Jarda-H** [pashok6798/TTG_Tools#11]
Hello, I don't know why it's happening, but everything is fine until you enter Atlastower.
When you talk to someone you can't hear audio and you can't see edited subtitles.

Original file: [env_09_atlastower_english.zip](https://github.com/pashok6798/TTG_Tools/files/6045698/env_09_atlastower_english.zip)
Simply repack of original txt file can reproduce this bug.
[Bug vid](https://www.youtube.com/watch?v=tu4dKm_u5pk)
[Original vid](https://youtu.be/S_kbLzXfv10?t=2962)

Settings:
![image](https://user-images.githubusercontent.com/62809719/109215649-bf768900-77b3-11eb-8f70-bb75e1dc757e.png)
Archive version: 1

[Tales from the Borderlands - save S3 Atlastower.zip](https://github.com/pashok6798/TTG_Tools/files/6045776/Tales.from.the.Borderlands.-.save.S3.Atlastower.zip)

**Comment by pashok6798** [comment]
For new borderlands you need build archive version 2, I think. I'll see your files later.

**Comment by pashok6798** [comment]
I rebuilt original file to compare with your file and it fits with your file. Try archive version 2. Maybe it will fix your problem.

**Comment by Jarda-H** [comment]
Tried, same result :(

**Comment by pashok6798** [comment]
Strange. Please send me your translated text.

**Comment by Jarda-H** [comment]
Well.. you can change only one string and it'll be causing the problem.
1485) SASHA is changed
TXT: [env_09_atlastower_english.zip](https://github.com/pashok6798/TTG_Tools/files/6054100/env_09_atlastower_english.zip)
Packed landb: [env_09_atlastower_english.zip](https://github.com/pashok6798/TTG_Tools/files/6054102/env_09_atlastower_english.zip)
I know you can't see much in file change, but it simply don't work in that scene. Every others are fine, so if it's some ttg bug only for that scene, maybe?
Anyway thanks for help!

**Comment by pashok6798** [comment]
That's funny... If you're using windows-1252 encoding you don't need use that option. Just set as "Normal unicode" and your file will be built successfully (don't rebuild old broken landb file. Better use original file).

**Comment by Jarda-H** [comment]
Other coding in new version didn't help (ASCII 1252, changed only one string, archive 2).
Even if i set coding to ASCII 1251 and coding for new TFTB.
So.. idk.

**Comment by pashok6798** [comment]
> //I can see subtitles in some parts of the scene (for example at the beginning), but some conversations are bugged like in the video from first comment. And again, it's happening only in this Atlastower scene

Latest parameters need for users with another encoding so you need use a normal unicode. You rebuilt your files or use original landb files and your text files?

**Comment by Jarda-H** [comment]
Yes, I'm packing original landb file exported form game files

**Comment by pashok6798** [comment]
[env_09_atlastower_english.zip](https://github.com/pashok6798/TTG_Tools/files/6054686/env_09_atlastower_english.zip)
Try this file.

**Comment by Jarda-H** [comment]
Yes, your file with changed header works fine!

**Comment by pashok6798** [comment]
You can try redownload v 1.0.6.

**Comment by Jarda-H** [comment]
Well.. downloaded and it don't work, even if I am rebuilded ttg tool from source code. I've tried also [landb5.exe from rengareng](https://forum.xentax.com/viewtopic.php?f=35&t=3254&start=420) for creating that problem file and it seems to work fine. So now it's up to you. If you have free time and you want to implement it to your tool or not, it'll be "nice to have" feature.
Anyway thanks much for your tool.
