### ISSUE TITLE
TTG Tools v1.0.6 - issue with fonts from Puzzle Agent

### ISSUE THREAD

**Issue by bartlomiejduda** [pashok6798/TTG_Tools#12]
Hello. I have tested v1.0.6 with fonts files from Puzzle Agent and it seems that font editor doesn't work properly.
Here is the screenshot with the error https://i.imgur.com/vinAfdU.png

And here are the font files samples for you to check
https://drive.google.com/file/d/1eGAAND2v8lcKwHoPBcESNu6hLvS150DK/view?usp=sharing

Could you please fix this issue?

Also, is there any workaround for this?

**Comment by pashok6798** [comment]
Hello. I'll see when I have free time.

**Comment by pashok6798** [comment]
LOL. That was a silly bug. Try this fix: 
[TTG Tools font FIX.zip](https://github.com/pashok6798/TTG_Tools/files/6097186/TTG.Tools.font.FIX.zip)

**Comment by bartlomiejduda** [comment]
It seems that it works with this fix, thanks. :)

**Comment by pashok6798** [comment]
> It seems that it works with this fix, thanks. :)

You're welcome. Maybe next version it will be fixed.
