### ISSUE TITLE
Minecraft story mode season 2

### ISSUE THREAD

**Issue by I-love-cmd** [pashok6798/TTG_Tools#13]
Hey, I'm maybe stupid, but i can't see key select for Minecraft story mode season 2. I see only Minecraft: story mode. Can you help me please, thanks.

**Comment by pashok6798** [comment]
Hello. Strange. I thought that I've added key. I'll see key in ttarchext and I'll send to you. After that I'll add it to my tool.

**Comment by pashok6798** [comment]
You can enter this key in "custom key" field: 8cd29b9987de94a9e69ea5947fcec1bccc9c8eddb1a7669fb28addba9cdec29ad377627faecca7d1d8e6d9d2ab64829f92cc9498d3e4a0

**Comment by I-love-cmd** [comment]
Ye, works fine. Ty!
