### ISSUE TITLE
Tutorial Help

### ISSUE THREAD

**Issue by ubszzz** [pashok6798/TTG_Tools#14]
I want tutorial the walking dead translate game

**Comment by pashok6798** [comment]
Which language you want translate?

**Comment by ubszzz** [comment]
> Which language you want translate?

Thai language

**Comment by pashok6798** [comment]
Oh... I may try help you with remastered version of the Walking Dead if I'll have free time but I'm not sure that I can help you with original first games (1, 2 seasons and DLC 400 Days because it used ASCII encoding and I don't know which your codepage in windows. I found only TIS-620 standart but our tool doesn't support this standart).

**Comment by ubszzz** [comment]
thank you

**Comment by ubszzz** [comment]
> Oh... I may try help you with remastered version of the Walking Dead if I'll have free time but I'm not sure that I can help you with original first games (1, 2 seasons and DLC 400 Days because it used ASCII encoding and I don't know which your codepage in windows. I found only TIS-620 standart but our tool doesn't support this standart).

Thank you

**Comment by pashok6798** [comment]
First you need set up tool. Make parameters like this:
![image](https://user-images.githubusercontent.com/27864883/119254669-3effd280-bbc0-11eb-9642-96b3b6603d7f.png)
Then with ttarchext and command line extract landb files and font files (if you want redrawing textures then extract d3dtx files and use a plugin NVIDIA Texture Tool for Photoshop CS6).
After extraction open "Auto(De)Packer" in TTG Tools. You'll see this window:
![image](https://user-images.githubusercontent.com/27864883/119254720-a158d300-bbc0-11eb-88b9-f53a54320a1b.png)
Move extracted resources into input folder and click "Decrypt, Extract" button. Some fonts in remastered version are vectored and some fonts are bitmapped so if you'll see message like this:
![image](https://user-images.githubusercontent.com/27864883/119254770-f4cb2100-bbc0-11eb-8d7a-fe7e6a89c02c.png)
That means that you'll need use Font Editor in TTG Tools and BMFont from Angel Code: https://www.angelcode.com/products/bmfont/
In BMFont set up these parameters:
![BMFont parameters](https://user-images.githubusercontent.com/27864883/119254849-55f2f480-bbc1-11eb-9fd6-a8ec637c317b.png)
Then select needed characters (or you can just select all chars from font but it will be slower) and then select "Export Options" in BMfont:
![image](https://user-images.githubusercontent.com/27864883/119255163-ce0dea00-bbc2-11eb-9c7d-803955118750.png)

I'll try write next part for working with files.

**Comment by pashok6798** [comment]
After that save font and open needed font in Font Editor.
Here's example opened font:
![image](https://user-images.githubusercontent.com/27864883/119255232-483e6e80-bbc3-11eb-8905-d7a3a90199f1.png)
First you need replace texture. Click on needed texture (in example here's only one texture but in another fonts may be several textures. It's okay if in your font would be less textures than in font. You can just don't replace not needed textures. If your font has more textures than game font then try change size textures to make font with less textures) and select "Import texture". Select needed texture. After that select this option:
![image](https://user-images.githubusercontent.com/27864883/119255332-e9c5c000-bbc3-11eb-82eb-d468b487b435.png)
You'll see green coordinates. Save this font and move it into a prepared build folder.

**Comment by pashok6798** [comment]
Return to "Auto(De)Packer" window.

If you moved into input folder landb and d3dtx files and extracted it already, you'll see extracted resources in output folder. landbs will be in text files (.txt) and d3dtx files will be in DDS format.
Recommend edit text files in Notepad++ or another notepads except window's notepad.
After changing resources move you txt and dds files into input folder with landb and d3dtx files then in Auto(De)Packer click "Encrypt, Pack, Import" button.
You'll see next messages:
![image](https://user-images.githubusercontent.com/27864883/119255578-41b0f680-bbc5-11eb-83db-9e720c59ff65.png)
It means that you can move imported landb and d3dtx files from output folder into folder to build archives.

**Comment by pashok6798** [comment]
With "Archive Packer" you can build/rebuild archives. Recommend set up these parameters:
![image](https://user-images.githubusercontent.com/27864883/119255654-9c4a5280-bbc5-11eb-8740-737f1a344378.png)
In "Input folder" select your build folder and in "Output archive" select path to archive which will be created.
Click "Build" button and wait until tool builds archive.

**Comment by pashok6798** [comment]
Decrypt lua script you can decrypt with Auto(De)Packer. Move lua script into Input folder and select next options:
![image](https://user-images.githubusercontent.com/27864883/119257356-9bb5ba00-bbcd-11eb-8420-93c11884a9c4.png)
With notepad++ you can edit lua scripts.
![image](https://user-images.githubusercontent.com/27864883/119257524-429a5600-bbce-11eb-854f-5f616c0955bb.png)
After editing you can encrypt it back by replacing lua files in input folder and click "Encrypt, Pack, Import" button in Auto(De)Packer.

There are script examples: 
[Output.zip](https://github.com/pashok6798/TTG_Tools/files/6527939/Output.zip)
I hope I helped you. Good luck!
