### ISSUE TITLE
TWD 1 Hungarian translate

### ISSUE THREAD

**Issue by ilovecoding69420** [pashok6798/TTG_Tools#17]
Sup,
If I want to pack translation with current tool it doesn't work (Only archive pack is ok, Auto(De)Packer is the problem.). It works for few files with old TTG tools v.0.6.1 until the old TTG version crashes. (that means: if i use the old tool to pack .landb files and then pack it with the new tool everying works).
**Settings:**
- .txt files have to be in ANSI or the game will crash on start up
- ASCII in old tool is set to 1251
- New tool packing - ttarch, version >2, dont use compress - key set to 50 (Walking Dead: the game)
Can you help me please? Thanks.

**Comment by pashok6798** [comment]
Hello. Which game are trying translate? Original WD on PC or from Definitive edition? The current version must be supported but you need txt files with UTF8. ANSI doesn't support anymore.

**Comment by ilovecoding69420** [comment]
Yes, original game. TWD Season 1. I tried to pack it with UTF-8 encode but menu won't load and the game crashes

**Comment by pashok6798** [comment]
Send your txt and landb files. And if you have an original files send it, too.

**Comment by ilovecoding69420** [comment]
[menu.zip](https://github.com/pashok6798/TTG_Tools/files/7803878/menu.zip)

**Comment by pashok6798** [comment]
Did you try set ASCII from 1251 to 1250?

**Comment by pashok6798** [comment]
[TTG Tools.zip](https://github.com/pashok6798/TTG_Tools/files/7805847/TTG.Tools.zip)
Try it.

**Comment by ilovecoding69420** [comment]
ASCII 1250 with the new tool works like a charm, thanks a lot! Maybe consider to set ASCII 1250 as default when packing TWD1
