### ISSUE TITLE
lenc depack

### ISSUE THREAD

**Issue by ilovecoding69420** [pashok6798/TTG_Tools#18]
Sorry to bother you again but I think i found another bug or something. When I want to depack S2 lenc to lua, it just give me file with `LuaQ  6` header in it. No plain text as in other ttg games. Thanks for your time! Original boot lenc attached as an example.
[original boot.zip](https://github.com/pashok6798/TTG_Tools/files/7831722/original.boot.zip)

**Comment by pashok6798** [comment]
Hi. In older versions you had to change values with hex editor, except iOS versions, so it's not a bug and I don't know how to decompile and compile these scripts.

**Comment by ilovecoding69420** [comment]
Ok, I somehow managed to unpack it and then compile it.
But now i have a problem with packing landb+txt.
ASCII 1250 and it works only in v1.0.4. Not with the newest version (When I start the game it just wount load - black screen).

**Comment by pashok6798** [comment]
Try this:
[Fix.zip](https://github.com/pashok6798/TTG_Tools/files/7835003/Fix.zip)

**Comment by ilovecoding69420** [comment]
Works. Thanks for your amazing help! That's all, everything i need works.
