### ISSUE TITLE
Can't export coordinates from TFTB fonts

### ISSUE THREAD

**Issue by ilovecoding69420** [pashok6798/TTG_Tools#19]
Hey, I can't even open the font in new version (1.0.9) - no error, it just won't load at all - interesting.
Anyway... It loads fine in 1.0.6 but I can't export coordinates.
Thanks.
[Bevan.zip](https://github.com/pashok6798/TTG_Tools/files/7899548/Bevan.zip)
![image](https://user-images.githubusercontent.com/97043299/150189958-c0845490-dceb-48c2-9752-2f896d87adbd.png)

Update: Texture export is also broken
![Bevan(0)](https://user-images.githubusercontent.com/97043299/150191296-0edfa0b8-a784-43fd-b751-b03fd232504e.png)

**Comment by pashok6798** [comment]
I couldn't fix correct read coordinates from this file. If I add support this font then other fonts don't work. If you have a vector font for this bevan, then you can generate it with bmfont generator and replace it in another font and save it as bevan.font. The current version automatically import textures if they have the same name as fnt file and it's nearby with fnt file. If you don't have vector font for bevan, I'll try to think how extract both coordinates and textures.

**Comment by ilovecoding69420** [comment]
Well.. that'll be super cool. I need to
- export coordinates - change few chars to my lang - import them back
- i can export texture from PC version, that's ok - but I still need to import it back to this Nintendo version
And if you want I can send you more fonts from Nintendo version. Thanks.

**Comment by pashok6798** [comment]
Which current your config in TTG Tools? I'll try generate bevan font.

**Comment by pashok6798** [comment]
Please send worked font which current version can open.

**Comment by pashok6798** [comment]
[Experimented version tool and font.zip](https://github.com/pashok6798/TTG_Tools/files/7961415/Experimented.version.tool.and.font.zip)

Try this font and if it will successfull vork you can open font Nintendo Switch version and replace coordinates and textures with modified tool.

**Comment by ilovecoding69420** [comment]
I'm so sorry for the delay. I was on vacation.
I'll try and i'll let u know.

**Comment by ilovecoding69420** [comment]
![image](https://user-images.githubusercontent.com/97043299/151658794-0ddc557f-925d-4b78-840d-9766ef49bb32.png)
I changed texture and then i exported and changed coordinates (Overwritten id). I'm using the Import from Bitmap font generator (cuz there isn't any other option to import), so maybe that's the problem.
[changed cords, texture - but not imported to font.zip](https://github.com/pashok6798/TTG_Tools/files/7964219/changed.cords.texture.-.but.not.imported.to.font.zip)

**Comment by pashok6798** [comment]
Why after 000 I see some 2 blocks by 8 bytes? After changing I don't see it.
[Willow_test.zip](https://github.com/pashok6798/TTG_Tools/files/7965445/Willow_test.zip)

**Comment by pashok6798** [comment]
[test.zip](https://github.com/pashok6798/TTG_Tools/files/7965464/test.zip)
Try this. If you will replace bevan font on nintendo switch don't forget resave texture into DXT5 format! I saved in ARGB8888 format but this tool doesn't support swizzle of uncompressed textures.

**Comment by ilovecoding69420** [comment]
It's same again :( Even when i converted dds to DXT5 and then imported

**Comment by pashok6798** [comment]
OK. Good luck.

**Comment by ilovecoding69420** [comment]
Thanks! Fonts are working just fine.
