### ISSUE TITLE
Problem in creating new fonts

### ISSUE THREAD

**Issue by Detector-I** [pashok6798/TTG_Tools#20]
Hi thank you for good tool
I was trying to create a new font for a game name  **The Walking Dead Michonne** but looks like the tool cant work properly  with this type of font, when I create new font, game will just crash at startup, also as you can see it reading the texture w&h wrong too, look like its 1byte ahead of file itself...
![image](https://user-images.githubusercontent.com/18105381/155389489-b7d6a232-dcab-47df-8ffb-1a0c7144c150.png)

**Comment by pashok6798** [comment]
Hi. I don't have WD Michonne so I couldn't test my current version tool on this game. Please send me some d3dtx textures and font files for research.

**Comment by Detector-I** [comment]
> Hi. I don't have WD Michonne so I couldn't test my current version tool on this game. Please send me some d3dtx textures and font files for research.

thank you for fast replay
here is some fonts, I check the file a little, looks like you tool at least reading the texture wrong, the width and height are incorrect...
[WDM_pc_Project_txmesh.zip](https://github.com/pashok6798/TTG_Tools/files/8127212/WDM_pc_Project_txmesh.zip)

**Comment by pashok6798** [comment]
OK. I'll try find out later.

**Comment by pashok6798** [comment]
[TTG Tools Michonne fix.zip](https://github.com/pashok6798/TTG_Tools/files/8134927/TTG.Tools.Michonne.fix.zip)
I'm not sure that it will work properly but try this fix.

**Comment by Detector-I** [comment]
> [TTG Tools Michonne fix.zip](https://github.com/pashok6798/TTG_Tools/files/8134927/TTG.Tools.Michonne.fix.zip) I'm not sure that it will work properly but try this fix.

thank you, with the new version game can now read and load the new font.
but there is still one problem
Original font
![image](https://user-images.githubusercontent.com/18105381/155621463-d6d53996-eba8-44a2-88b9-2aea06ddfdf2.png)
the new created font with the tool
![WalkingDeadMichonne_NbwgFHwjc3](https://user-images.githubusercontent.com/18105381/155621774-e09f00b1-1238-400e-ac99-7bb99a1eef33.jpg)
as you can see there is extra spacing at top... maybe you are calculating the yoffset a little wrong in the tool?

**Comment by pashok6798** [comment]
Please send me your generated font files and I'll compare it later.

**Comment by Detector-I** [comment]
> Please send me your generated font files and I'll compare it later.

here a font I created (also a font from the game that I imported font to it)
[font.zip](https://github.com/pashok6798/TTG_Tools/files/8140641/font.zip)

**Comment by pashok6798** [comment]
[TTG Tools Michonne fix.zip](https://github.com/pashok6798/TTG_Tools/files/8142149/TTG.Tools.Michonne.fix.zip)
Try reimport fonts with this version.

**Comment by Detector-I** [comment]
> [TTG Tools Michonne fix.zip](https://github.com/pashok6798/TTG_Tools/files/8142149/TTG.Tools.Michonne.fix.zip) Try reimport fonts with this version.

thank you very much, the problem seems to fixed.
![image](https://user-images.githubusercontent.com/18105381/155742101-fef03009-ab4c-45be-9b72-a61c73287bbf.png)
Thanks for the quick support 👍
I believe the problem fixed, so I will close the issues.
