### ISSUE TITLE
Problem with Lua and prop file in WD Michonne

### ISSUE THREAD

**Issue by YouKnow-sys** [pashok6798/TTG_Tools#21]
Hi, when I try to use **Auto (De)Packer** for decrypt and export prop and lua files of WD Michonne it fail.
for prop file it will say `Unknown prop file`
but for lua files, sometime it will export them without problem, some other time it will output wrong and incorrect data, and some other time tool will just crash in the process...
I will attach some example of prop and lua files.
[input.zip](https://github.com/pashok6798/TTG_Tools/files/8179660/input.zip)

**Comment by pashok6798** [comment]
TTG Tools supports only two prop files from Walking Dead Season one original. Another prop files this tool doesn't support, sorry.

Try check option "Encrypt new version lua files".

**Comment by YouKnow-sys** [comment]
> TTG Tools supports only two prop files from Walking Dead Season one original. Another prop files this tool doesn't support, sorry.
> 
> Try set checkbox option "Encrypt new version lua files".

thank you for answers.
I tried the mentioned option, but sadly it didn't helped (its still crash and or output incorrect files.)
also I tested it with every possible setting that I can think of, but still result was the same...

**Comment by pashok6798** [comment]
Please send screenshot your current parameters

**Comment by YouKnow-sys** [comment]
> Please send screenshot your current parameters

![Output is incorrect](https://user-images.githubusercontent.com/17937017/156640668-c61cafd0-8e95-403a-8e5c-008032fbb7a7.png)
![incorrect again](https://user-images.githubusercontent.com/17937017/156640809-dbf2fd1e-8d18-436e-8989-2bb918e8f165.png)
also tried both without checking the `Encrypt new version lua files`

**Comment by pashok6798** [comment]
Oh. You mean that after decryption Lua file looks like some trash symbols instead normal Lua code? TTG tools just decrypt/encrypt Lua files, not decompile/compile.

**Comment by YouKnow-sys** [comment]
btw by any chance you know what compiler game used? seems like it didn't used LuaJIT

**Comment by pashok6798** [comment]
I saw header and it was 0x52. Seems it was Lia 5.2. Try this version. I tried and with my scripts game crashed.

**Comment by YouKnow-sys** [comment]
managed to decompile and compile it back, thank you (yet not tested in game...
btw have any idea where they could store the code that used to create the typing style in subtitle..? I would love to try and remove it...

**Comment by YouKnow-sys** [comment]
![image](https://user-images.githubusercontent.com/17937017/156662239-d5f518f3-21c5-469d-8c6a-e6c83f6cf849.png)
well I just decompile and compile a file just for testing...
and yes it broke the game

**Comment by pashok6798** [comment]
I saw that somebody tried make Lua editor for a walking dead season 4 (?) but I didn't see their results. You can try search on GitHub project. I can't remember project's name so you can try search by key words like telltale Lua or something.

**Comment by YouKnow-sys** [comment]
I think this is as far as I can go...
I can find what im looking for... (there is no problem in editing scripts itself)
I think its on engine itself sadly...
anyway thank you for all helps.
