### ISSUE TITLE
TTG Tools temporary (I hope) won't support

### ISSUE THREAD

**Issue by pashok6798** [pashok6798/TTG_Tools#22]
Hey, everyone!
Due political issues between Russia and Ukraine and some problems with blocking some sites I've decided release current version TTG Tools and temporary stop support this tool. If political problems won't be solved, you can fork our tool and continue support it. I won't remove this repository. I'm sorry for this news. I hope that current world position will be solved peaceful and I continue support this tool.

P.S. Sorry for my bad english (I know, it sucks).

**Comment by ilovecoding69420** [comment]
I hope so too. War is a bad thing.

**Comment by pashok6798** [comment]
I heard that some russian's repositories are removing now so I'd prefer copy my sources on my HDD and if my repository will be removed, I hope, you can find forks of my tool.

**Comment by pashok6798** [comment]
I'll try sometimes fix something but source code will be updated on GitFlic (russian analog of github). I'll try upload compiled files here, too.
