### ISSUE TITLE
Broken font editor (v1.0.9 and v1.0.10)

### ISSUE THREAD

**Issue by bartlomiejduda** [pashok6798/TTG_Tools#23]
Hi, I have this font from Telltale's Batman game:
https://drive.google.com/file/d/1A1oUcrO6YM6LtrNGhZOpDjNXpv874524/view?usp=sharing

It can't be opened in TTGTools v1.0.9 and v1.0.10. **No error message is shown while trying to open.**

But **it works fine in TTGTools v1.0.7**. It can be opened and edited using built-in font editor. So something went wrong with the newest commits.

Can it be fixed?

**Comment by pashok6798** [comment]
[TTG Tools fix.zip](https://github.com/pashok6798/TTG_Tools/files/8645743/TTG.Tools.fix.zip)
Try this fix

**Comment by bartlomiejduda** [comment]
Fix solved the issue. Thanks.

**Comment by pashok6798** [comment]
You're welcome!
