### ISSUE TITLE
Unicode with polish words.

### ISSUE THREAD

**Issue by PrawyCoD1** [pashok6798/TTG_Tools#24]
Hello,

Everytime when i encrypt .landb files that has polish letters: ŻÓŁĆĘŚĄŹŃ żółćęśąźń, they got changed into �.
Can you fix it please? Would be very helpful.

Regards,
Prawy

**Comment by Jarda-H** [comment]
Hey, try doing this:
- Set right ASCII 1251/1252
- Select Normal Unicode radio button
- Check Unicode support box in auto depacker

**Comment by PrawyCoD1** [comment]
> Hey, try doing this:
> 
> * Set right ASCII 1251/1252
> * Select Normal Unicode radio button
> * Check Unicode support box in auto depacker


I've tried ASCII 1250/1251/1252 it didn't help me.

I have normal unicode picked also i have picked unicode support

**Comment by PrawyCoD1** [comment]
![image](https://user-images.githubusercontent.com/70172890/167310724-161bdc8d-2fb7-4f67-b299-5ec29a0e6927.png)

Okay, this settings fixed my issue! :)
