### ISSUE TITLE
Settings bug

### ISSUE THREAD

**Issue by PrawyCoD1** [pashok6798/TTG_Tools#25]
Hello,

Everytime when i save settings like on screenshot it stays like that.
![image](https://user-images.githubusercontent.com/70172890/167388429-7e9505d6-9f8d-42da-9412-3c1b429271e5.png)

But after using encrypt,pack,import it's changing to:
![image](https://user-images.githubusercontent.com/70172890/167388488-ee926c0d-e8af-48e1-8367-6109c95dd9ec.png)

I need it to be set as NOT NORMAL UNICODE(uses aditional char) because only then there is polish letters inside landb,txt files.

Can you fix it?

**Comment by pashok6798** [comment]
Hi. I recommend use second option because it change into normal windows-1252 format. Old method just changed some characters by adding 0xD3 char. I planned remove that oldest option in newer versions.
