### ISSUE TITLE
FONT Addition Problem

### ISSUE THREAD

**Issue by skalia16** [pashok6798/TTG_Tools#26]
Hello, I want to add fonts for Tales of Monkey Island to the game.
Bitmap Font Generator I did everything as in the thread here.
But the places of the letters in the game are different. For example, instead of the letter "A", the letter "F" is written.
After creating FONT with Bitmap Font Generator, do I need to manually edit the coordinates in the .fnt file?

https://github.com/pashok6798/TTG_Tools/issues/14

**Comment by pashok6798** [comment]
Hi.
Did you try set these parameters in BMFont generator?
![2022-07-11_19-25-30](https://user-images.githubusercontent.com/27864883/178314902-c4aa69ae-98df-474c-b10e-352ea555b324.png) ![2022-07-11_19-31-54](https://user-images.githubusercontent.com/27864883/178314906-0df0f14d-ae4a-4536-b385-b76ee2b5349e.png)

You can try my test fnt and dds files.
[test font.zip](https://github.com/pashok6798/TTG_Tools/files/9086015/test.font.zip)

**Comment by skalia16** [comment]
Do you have an idea, please?

**Comment by skalia16** [comment]
No, where exactly should I do this? I couldn't find the place.

**Comment by pashok6798** [comment]
You need font as original or I can generate font from Arial?

**Comment by Jarda-H** [comment]
> Could you please create a FONT with Turkish characters such as ç,ö,ü,ş,ğ,ı?

You can use [FontForge](https://fontforge.org/en-US/) to add your letters.

**Comment by skalia16** [comment]
> Orijinal olarak yazı tipine mi ihtiyacınız var yoksa Arial'den yazı tipi oluşturabilir miyim?

It doesn't matter, you can make any font you want. Thank you for your interest.

**Comment by skalia16** [comment]
> > Lütfen ç,ö,ü,ş,ğ,ı gibi Türkçe karakterlerden oluşan bir FONT oluşturur musunuz?
> 
> Harflerinizi eklemek için [FontForge'u](https://fontforge.org/en-US/) kullanabilirsiniz . Veya ttf'de yazı tipiniz yoksa, DDS dokusunu düzenleyebilirsiniz (kullanılmayan harfleri değiştirin, bunları sizinkiyle değiştirin ve ardından karakter kimliğini düzenleyin).

Yes it can be done by changing the existing letters in the DDS file but I would like to add it without the need if possible.

**Comment by pashok6798** [comment]
OK, I'll think about that.

**Comment by pashok6798** [comment]
Try this font. I used generated arial font.
[weathered_sf_30.font.zip](https://github.com/pashok6798/TTG_Tools/files/9173266/weathered_sf_30.font.zip)

**Comment by skalia16** [comment]
Thank you very much for your help :) If you don't mind, can you tell me what settings you are using for this font? I wanted to ask to use it in different games in the future.

**Comment by pashok6798** [comment]
Settings like his but I set Turkish instead ANSI,
https://github.com/pashok6798/TTG_Tools/issues/26#issuecomment-1180633406

**Comment by skalia16** [comment]
Thank you. Thank you very much for your help and interest. I am very grateful to you.

**Comment by pashok6798** [comment]
So I can close your issue?
