### ISSUE TITLE
Have some problem with Back To The Future font modding

### ISSUE THREAD

**Issue by kamnanrock** [pashok6798/TTG_Tools#27]
Hello, I have some problem with Back To The Future font modding, I want to translate to Thai. So, I add the font into the game and your program can't add Thai language into the Back To The Future .font file. But the other game like The Walking Dead can add it and work finely. How can I fix it???

Here's a font from Back To The Future The Game
https://drive.google.com/file/d/1GcUzzSnjwatfBfJ-JWUFKKTSiyTVlDMN/view?usp=sharing

**Comment by pashok6798** [comment]
Hello. I can't check your fonts right now. I'll try check after October, 20th.

**Comment by pashok6798** [comment]
Hi. I tried set a specific windows encoding support. You can try set checkbox on "Specific ASCII encoding" and click "Apply" or "Apply and exit". Then you can try replace fonts into your encoding. And please check support encoding in export/import texts. I can't check it in my windows version.
[Test thai version.zip](https://github.com/pashok6798/TTG_Tools/files/9792806/Test.thai.version.zip)

**Comment by kamnanrock** [comment]
Hi, I can't checkbox on "Specific ASCII encoding". I check it, apply and exit, it reset when I re-open. And how can I check support encoding texts???

**Comment by pashok6798** [comment]
Yes. It must be your encoding now. I didn't know how better make settings for your encoding. If current method will work, I'll think about set your encoding via ASCII number counter.

**Comment by kamnanrock** [comment]
Ok, thank you so much

**Comment by pashok6798** [comment]
Please leave me commentary about current version. I want to know does it work method correctly or I need to solve problems. Please check fonts and how replace text in game.

**Comment by pashok6798** [comment]
Wait. Telltale explorer can replace landb files? I thought it can only extract and convert some telltale's resources into txt, tga and wav files.

**Comment by kamnanrock** [comment]
It can repack txt files to a landb files too

**Comment by pashok6798** [comment]
Can I close issue? I solved your issue?

**Comment by kamnanrock** [comment]
Sure, go ahead. Thank u so much!!!
