### ISSUE TITLE
The Walking Dead Android

### ISSUE THREAD

**Issue by aZ4ziL** [pashok6798/TTG_Tools#32]
In the Walking dead season 3: A new frontier. I extraxt WD_302***.data.ttarch2 with ttarchext.exe. Than I get the landb file to decrypt with TTG TOOLS.

After I finished translating the language from English to Indonesian and I encrypted using the TTG tool again. And I started building again using TTG tools with version 1 and extract. When I paste the file into android and start to test whether it runs or not. But the game only runs on the main menu, after entering and selecting an episode, namely in episode 2, it just loads and doesn't enter the game.

Please help me how to translate the walking dead Android game, give me the steps that must be done. And if you may know how to extract the Walking dead OBB file on Android 

Thank You:)

**Comment by pashok6798** [comment]
Hi. Did you try select version 2 and build archive? Dou you have lia scripts in your archive? Lua scripts mustn't be encrypted on mobile versions.

**Comment by PrawyCoD1** [comment]
Why would you try to translate android version. It's pretty hard to do just because you need root to replace all the files. Not everyone can root their devices in order to use translation. So i'm curious

**Comment by aZ4ziL** [comment]
> Hi. Did you try select version 2 and build archive? Dou you have lia scripts in your archive? Lua scripts mustn't be encrypted on mobile versions.

BEFORE IT. I am sorry to reply your comment.

yes i have a lua script. And some landb files. To decrypt ttach2 I succeeded via ttachext.exe, when I wanted to encrypt it it worked but the Game Launcher application would not run or read it. it just takes a long time to load and might get stuck.

**Comment by aZ4ziL** [comment]
> Why would you try to translate android version. It's pretty hard to do just because you need root to replace all the files. Not everyone can root their devices in order to use translation. So i'm curious

Sorry, this does not necessarily require root privileges. Because the additional files from the Walking Dead android game are located at Android/obb/filename.obb. What I'm having trouble with is decrpt and encrypt the obb and ttarch2 files.

**Comment by PrawyCoD1** [comment]
> > Why would you try to translate android version. It's pretty hard to do just because you need root to replace all the files. Not everyone can root their devices in order to use translation. So i'm curious
> 
> Sorry, this does not necessarily require root privileges. Because the additional files from the Walking Dead android game are located at `Android/obb` filename.obb. What I'm having trouble with is decrpt and encrypt the obb and ttarch2 files.

Yes that's true, but the files inside of 'Android/obb' are files reponsible just for episode 1, main menu and pause menu of episode 1 rest is located inside of folders that needs root privileges
