### ISSUE TITLE
6VSMP landb files cannot be encrypted 

### ISSUE THREAD

**Issue by PrawyCoD1** [pashok6798/TTG_Tools#33]
Hey,
i can decrypt,export 6VSMP landb file but i can't encrypt it back from .txt to landb file.

In this release this wasn't an issue: https://github.com/pashok6798/TTG_Tools/releases/tag/v1.0.12

Please fix it! I'm attaching landb file i'm talking about down below.
![image](https://user-images.githubusercontent.com/70172890/220210153-4538cd4c-3ba4-4176-8a47-0935907d7fef.png)
https://anonymfile.com/NV1K1/env-previouslyonenglish.landb

**Comment by pashok6798** [comment]
Sorry but I can't download your file. Please send me in zip file right here.

**Comment by pashok6798** [comment]
https://github.com/pashok6798/TTG_Tools/releases/tag/v1.11 - try this version.
