### ISSUE TITLE
please ADD support for batman arkham asylum .font & Texture2d

### ISSUE THREAD

**Issue by ramyzahran** [pashok6798/TTG_Tools#34]
hi thanks for this great utility TTGTools, i hope you will ADD support for batman arkham asylum .font & Texture2d, i tried editing batman arkham asylum .font files but the tool crashed,..
please HELP,
thank you deeply
[MediumFont.zip](https://github.com/pashok6798/TTG_Tools/files/10920793/MediumFont.zip)

**Comment by pashok6798** [comment]
Hi. I'm sorry but this tool for games by Telltale. They made their first games with own tools which called Telltale Tool. Your game was made on Unreal Engine 3. You can try make own fonts and try generate archive with UDK (Unreal Development Kit). Don't forget add your archive at ini list. I can't remember in which ini file you need add your archive. Try ask on xentax or zenhax forums.
