### ISSUE TITLE
Doesn't worth with Skunkape's ".dlog" files.

### ISSUE THREAD

**Issue by Benjamoose** [pashok6798/TTG_Tools#35]
As the title says, the tool works for some other files with Skunkape's games, but not ".dlog".

![image](https://user-images.githubusercontent.com/32703517/233796859-047d64af-60fc-4267-b3a2-85ee1107e971.png)

I've attached some .dlog files below for you to look at:
[.dlog files](https://github.com/pashok6798/TTG_Tools/files/11301843/store_sam_bosco.zip)

**Comment by pashok6798** [comment]
Hi. You don't need change dlog files in games from Skunkape games studio. You need extract and repack landb files.

**Comment by pashok6798** [comment]
I'm sorry but I can't find out structure of dlog and chore files. They have a complicated structure so I could make search parameters time and another parameter for timings in chore file. I've made a raw tool for skunkape game chore timing editor. It can change timings in chore files and also can change timing some mouth animations in cutscene.

**Comment by pashok6798** [comment]
I'm not sure about anm files. I've just found count of key values and just change timings for these key values. I hope some easy animations probably extract and replace it in newer versions.
