### ISSUE TITLE
Game Tutorial

### ISSUE THREAD

**Issue by Boxmark00** [pashok6798/TTG_Tools#36]
So uh, with this tool I could make games similar to those made by TTG? Or its for asset extraction from their games?

**Comment by pashok6798** [comment]
Hi. You can extract/replace text, textures and fonts with that tool.

**Comment by Boxmark00** [comment]
> Hi. You can extract/replace text, textures and fonts with that tool.

I see, but has been the Telltale tool/engine ever been released on the internet?

**Comment by pashok6798** [comment]
> I see, but has been the Telltale tool/engine ever been released on the internet?
I don't know. Now Telltale tool may be called as Skunkape tool.
