### ISSUE TITLE
The wolf among us

### ISSUE THREAD

**Issue by MohammedXD29** [pashok6798/TTG_Tools#38]
Hi Again, sorry for what happend Then, I made a font for The wolf among us and it worked but the problem is the text it begins from left to right I want it from right to left or anything that could make it not begin from left to right.

**Comment by ramyzahran** [comment]
I hope i can make a font for batman Arkham asylum with this tool

**Comment by MohammedXD29** [comment]
> I hope i can make a font for batman Arkham asylum with this tool

رامي, قلت لك TTG TOOLS مو لباتمان

**Comment by ramyzahran** [comment]
> > I hope i can make a font for batman Arkham asylum with this tool
> 
> رامي, قلت لك TTG TOOLS مو لباتمان

ربنا كريم وانا اسعى وأن ليس للإنسان إلا ما سعى

**Comment by pashok6798** [comment]
> I hope i can make a font for batman Arkham asylum with this tool

This tool doesn't support Batman Arkham asylum. You need try use Unreal Development Kit (UDK) or search font editor for unreal engine.

**Comment by pashok6798** [comment]
> Hi Again, sorry for what happend Then, I made a font for The wolf among us and it worked but the problem is the text it begins from left to right I want it from right to left or anything that could make it not begin from left to right.

I'm sorry but I can't do that. I even don't know which files shows subtitles from left to right.

**Comment by HavocDylanW** [comment]
> Hi Again, sorry for what happend Then, I made a font for The wolf among us and it worked but the problem is the text it begins from left to right I want it from right to left or anything that could make it not begin from left to right.

How do you making it work? I only got Unknown error everytime i tried to Depack it

**Comment by MohammedXD29** [comment]
> > Hi Again, sorry for what happend Then, I made a font for The wolf among us and it worked but the problem is the text it begins from left to right I want it from right to left or anything that could make it not begin from left to right.
> 
> I'm sorry but I can't do that. I even don't know which files shows subtitles from left to right.

Sorry for being late to answer, I made it with a hex editor by editing "ui_subtitles_text.prop"

**Comment by MohammedXD29** [comment]
> > Hi Again, sorry for what happend Then, I made a font for The wolf among us and it worked but the problem is the text it begins from left to right I want it from right to left or anything that could make it not begin from left to right.
> 
> How do you making it work? I only got Unknown error everytime i tried to Depack it

Use Telltale Explorer to extract the files and with TTG TOOLS you can edit text and font, open a issue or contact me on discord my account is (m7mdiq)
