### ISSUE TITLE
Questions about TTG tools

### ISSUE THREAD

**Issue by DalimOh** [pashok6798/TTG_Tools#39]
Hi!
I have a couple of questions about this tool.

Firstly, how does text editor exactly work?
There are 3 options: merge/replace/check-non...
What do they do?
What should I fill in in the blanks?

Secondly, I'm trying to translate with Korean.
What ASCII number should I use?
It's not in the how-to-use.

**Comment by pashok6798** [comment]
Hi. Text editor need for merge original and translated files into file with original + translated strings. Replace needs if you have original + translated files but in newer file has new strings so you can replace old strings and then translate new strings yourself.

If you need get strings you need use Auto (De) Packer.

**Comment by pashok6798** [comment]
> What should I fill in in the blanks?

Which blanks?

**Comment by pashok6798** [comment]
I don't know about Korean ASCII encoding. Which game you want translate? This option need for games before tales from the borderlands and games of thrones.

**Comment by DalimOh** [comment]
> > What should I fill in in the blanks?
> 
> Which blanks?

Blanks that were next to First/Second Files.
Was not sure about the placing order, but I guess now I know how to do

**Comment by DalimOh** [comment]
> I don't know about Korean ASCII encoding. Which game you want translate? This option need for games before tales from the borderlands and games of thrones.

I'm trying to translate Batman series 1 & 2, using english text file for my base file to korean.
However, seeing your comment, I think there would be no problem at all.
Thank you!

**Comment by pashok6798** [comment]
Batman must be work correct if you set "normal unicode".

**Comment by DalimOh** [comment]
> Batman must be work correct if you set "normal unicode".

Thank you! It works very well.
