### ISSUE TITLE
The Walking Dead season 1

### ISSUE THREAD

**Issue by JardaH69** [pashok6798/TTG_Tools#6]
You have it in supported game, but it isnt in program :(

**Comment by pashok6798** [comment]
What's wrong?

**Comment by pashok6798** [comment]
Which files tool doesn't support? landb, font or d3dtx?

**Comment by pashok6798** [comment]
> You have it in supported game, but it isnt in program :(

@JadaH69 which files my tool doesn't support? And for which platform are you trying work? Android? Windows? iOS? PS4?

**Comment by JardaH69** [comment]
@JadaH69 .landb
If i use it, it doesn't support UTF-8 chars.  And Windows.

**Comment by JardaH69** [comment]
@pashok6798  .landb
If i use it, it doesn't support UTF-8 chars. And Windows.

**Comment by pashok6798** [comment]
If you translate original walking dead,  it won't support utf-8 charger.  Only ASCII. Remaster have to support utf-8, if you are setting "Normal unicode" in setting window. We had to make this terrible way when Telltale didn't support correctly utf-8 in "game of thrones" and "Tales from the borderlands".

**Comment by JardaH69** [comment]
Ye, It's ok. I replaced wrong chars with right one.
Can you please add that the program remembers selected fields and paths? For example in de(Packer) - game name and in Archive packer input/output path. If not it's ok.
Anyway thanks for your explanation and amazing software. :)

**Comment by pashok6798** [comment]
Okay.  I'll think about that when I'll have enough time. You're welcome :) Thanks to Den Em for accepting share his code and mod it.
