### ISSUE TITLE
Texture looking weird

### ISSUE THREAD

**Issue by MexicanPB** [pashok6798/TTG_Tools#9]
I am trying to mod Minecraft Story Mode but when I do, I get this texture 
![ui_dialog_controllerFacebuttonUp](https://user-images.githubusercontent.com/74111213/98448669-8e7a2780-20e2-11eb-988a-9d93c3d56626.png)

Is there any fix?

**Comment by pashok6798** [comment]
I'll see later.

**Comment by pashok6798** [comment]
Which version TTG Tools did you use? And what texture showes like this?

**Comment by MexicanPB** [comment]
I used Version 1.0.5, it's the Y Xbox button that I want to mod

**Comment by pashok6798** [comment]
Okay.  I'll try to see. Another textures works fine? Only one works incorrect?

**Comment by pashok6798** [comment]
Oh! And one thing. Please write me archive which you extracted with texture.

**Comment by MexicanPB** [comment]
![ui_faceButtonA_xbox](https://user-images.githubusercontent.com/74111213/101210586-97e7a880-362a-11eb-8379-1ccc5951e7aa.png)
This one is busted too, and this is The Walking Dead Season 2, the name of this file is ui_faceButtonA_xbox.d3dtx

This is what the texture is supposed to look like
![ui_dialog_facebutton_a](https://user-images.githubusercontent.com/74111213/101210946-3247ec00-362b-11eb-92e0-3334e568cb91.png)

**Comment by pashok6798** [comment]
I didn't found these buttons in archives. Can you send me these files for test here?

**Comment by pashok6798** [comment]
I found in WD2 ui_face_buttonY_xbox.d3dtx. In my version works fine. Try this version.
[TTG Tools.zip](https://github.com/pashok6798/TTG_Tools/files/5646920/TTG.Tools.zip)

**Comment by MexicanPB** [comment]
So I tried your version and it's still busted, oof

**Comment by MexicanPB** [comment]
Proof 
![Screenshot 2020-12-09 22-08-16 (2)](https://user-images.githubusercontent.com/74111213/101728412-3761cc80-3a6b-11eb-9f39-82aed68ae9b4.png)

**Comment by pashok6798** [comment]
Okay. I'll try to see later in game textures.

**Comment by pashok6798** [comment]
I can't find button for test. Which tool did you used for saving DDS? I used nvidia texture plugin for photoshop and PVR Tex Tool. I'll try DDS plugin for GIMP.

**Comment by pashok6798** [comment]
Here I used PVR tex tool (saved in BC3 linear without mip maps DDS format) and repacked modded textures by this version which I sent you. I modified A button in QTE.
[Button A QTE.zip](https://github.com/pashok6798/TTG_Tools/files/5674450/Button.A.QTE.zip)

Here is a proof.
![20201210195538_1](https://user-images.githubusercontent.com/27864883/101804131-4c4d6700-3b22-11eb-8a35-0b03399e5c57.jpg)

**Comment by MexicanPB** [comment]
Okay, I see. I use intel texture works for photoshop to save dds files

**Comment by MexicanPB** [comment]
Let me try PowerVR TexTool to see if that works

**Comment by MexicanPB** [comment]
Nvm, turns out the reason why the textures looked weird was that I was saving the textures with mipmaps. I save the textures without mipmaps and it worked. I think the tool has issues with textures with mipmaps. I will be closing this issue now, thanks for the help.
